version: ~> 1.0
language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - 1.4
    - nightly
notifications:
    email: false
matrix:
    allow_failures:
    - julia: nightly
git:
    depth: 99999
env:
    global:
    - PYTHON=conda
