version: ~> 1.0
language: julia
os:
    - linux
    - osx
env:
    global:
    - PYTHON=Conda
julia:
    - 1.0
    - 1.4
    - nightly
notifications:
    email: false
git:
    depth: 99999
jobs:
  allow_failures:
    - julia: nightly
  include:
    - if: branch = master OR tag IS present
      stage: "Documentation"
      julia: 1.4
      os: linux
      # disable global before_script in order not to install Compose twice
      before_script:
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                                   Pkg.instantiate()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip
